FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends procps python-is-python3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN python3 -m pip install --upgrade pip --no-cache-dir

RUN pip3 install fire pysnooper ome-zarr numpy tifffile==2023.1.23.1 ome-types lxml natsort pystackreg pandas
