name: image_process
channels:
  - conda-forge
  - defaults
dependencies:
  - python<=3.9 # otherwise dask-image issue see https://github.com/Azure/azure-cli/issues/20444#issuecomment-1009648464
  - dask-image
  - scikit-image>=0.18
  #- xlrd<=2.0.0
  - openpyxl
  - tifffile
  - pip
  - pandas
  - numpy
  - pip:
    #- apeer-ometiff-library
    - fire
    - ome-types
